language: go
go:
  - 1.2.1
before_script:
  - npm install
  - bower install
install:
  - go get github.com/gorilla/mux
  - go get github.com/jcelliott/lumber
script: grunt dist
notifications:
  email: false
